controllers:
    resource: ../../src/Controller/
    type: annotation

admin:
    resource: ../../src/Controller/Admin/
    type: annotation
    # toutes les url des routes définies dans src/Controller/Admin/
    # commencent par /admin
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
